namespace PoRedoImage.Client.Http;

/// <summary>
/// Holds the browser-session identity for outbound BFF calls (§6.9). One instance per WASM app
/// load, so <see cref="SessionId"/> is stable for the life of the tab and lets server logs correlate
/// every request from one kiosk session. Correlation IDs are per-request and generated by the handler.
/// </summary>
public sealed class ClientRequestContext
{
    public string SessionId { get; } = Guid.NewGuid().ToString("N");
}
